In [ ]:
import numpy as np

In [ ]:
myarr = np.array([[3,2,54,65]],np.int8)

In [ ]:
myarr[0,1]

np.int8(2)

In [ ]:
myarr.shape

(1, 4)

In [ ]:
myarr.dtype

dtype('int8')

In [ ]:
myarr[0,1] = 45

In [ ]:
myarr[0,1]

np.int8(45)

In [ ]:
myarr.shape

(1, 4)

In [ ]:
myarr

array([[ 3, 45, 54, 65]], dtype=int8)

In [ ]:
listarray = np.array([[1,2,3],[4,5,3],[2,8,7]])

In [ ]:
listarray

array([[1, 2, 3],
       [4, 5, 3],
       [2, 8, 7]])

In [ ]:
listarray.size

9

In [ ]:
listarray.shape

(3, 3)

In [ ]:
listarray.dtype

dtype('int64')

In [ ]:
listarray[0,1] = 45

In [ ]:
listarray

array([[ 1, 45,  3],
       [ 4,  5,  3],
       [ 2,  8,  7]])

In [ ]:
zeros = np.zeros((3,4))

In [ ]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arange = np.arange(15)

In [ ]:
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
lspace = np.linspace(1,50,10)

In [ ]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
emp = np.empty((4,6))

In [ ]:
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,1,0]])

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
x.sum(axis = 0 )

array([12,  8,  9])

In [ ]:
x.sum(axis = 1)

array([ 6, 15,  8])

In [ ]:
x.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [ ]:
x.flat

In [ ]:
for item in x.flat:
  print(item)

1
2
3
4
5
6
7
1
0


In [ ]:
x.ndim

2

In [ ]:
x.size

9

In [ ]:
x.nbytes

72

In [ ]:
one = np.array([1,2,3,4,5])

In [ ]:
one.argmax()

np.int64(4)

In [ ]:
one.argmin()

np.int64(0)

In [ ]:
one.argsort()

array([0, 1, 2, 3, 4])

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar.argmin()

np.int64(8)

In [ ]:
ar.argmax()

np.int64(6)

In [ ]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [ ]:
ar.argmax(axis = 0 )

array([2, 1, 1])

In [ ]:
ar.argmax(axis = 1)

array([2, 2, 0])

In [ ]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [ ]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar2 = np.array([[2,3,4],[3,5,6],[3,6,9]])

In [ ]:
ar2

array([[2, 3, 4],
       [3, 5, 6],
       [3, 6, 9]])

In [ ]:
ar + ar2

array([[ 3,  5,  7],
       [ 7, 10, 12],
       [10,  7,  9]])

In [ ]:
ar*ar2

array([[ 2,  6, 12],
       [12, 25, 36],
       [21,  6,  0]])

In [ ]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [ ]:
ar.sum()

np.int64(29)

In [ ]:
ar.max()

np.int64(7)

In [ ]:
ar.min()

np.int64(0)

In [ ]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [ ]:
np.count_nonzero(ar)

8

In [ ]:
import sys

In [ ]:
py_ar = [1,0,4,8]

In [ ]:
np_ar = np.array(py_ar)

In [ ]:
sys.getsizeof(1)*len(py_ar)

112

In [ ]:
np_ar.itemsize * np_ar.size

32

In [ ]:
np_ar.tolist()

[1, 0, 4, 8]